/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Cover = {
  _type: 'cover'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt: string
}

export type Figure = {
  _type: 'figure'
  asset?: SanityImageAssetReference
  media?: unknown
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  alt: string
  caption?: string
}

export type Slide = {
  _type: 'slide'
  title?: string
  body?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal' | 'h4' | 'h5'
    listItem?: 'bullet' | 'number'
    markDefs?: Array<{
      href: string
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  image?: Figure
  layout?: 'image-right' | 'image-left' | 'image-full' | 'text-only'
}

export type SanityFileAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  siteTitle: string
  tagline?: string
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  colophon?: string
  email?: string
  githubUrl?: string
  linkedinUrl?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  favicon?: {
    asset?: SanityFileAssetReference
    media?: unknown
    _type: 'file'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  coverTitle?: string
  subtitle?: string
  year?: string
  presentation?: 'inherit' | 'book' | 'manuscript'
  clothColor: 'bay-blue' | 'berkshires-green' | 'duckling-yellow' | 'independence-cranberry' | 'ink'
  coverMotif?: 'none' | 'double-rule' | 'centered-dot' | 'corner-rules'
  coverImage?: Cover
  summary?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href: string
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  liveDemoUrl?: string
  repoUrl?: string
  role?: string
  tools?: Array<string>
  slides: Array<
    {
      _key: string
    } & Slide
  >
  seoDescription?: string
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type ProjectReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'project'
}

export type Shelf = {
  _id: string
  _type: 'shelf'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  caption?: string
  itemStyle: 'book' | 'manuscript'
  order: number
  items?: Array<
    {
      _key: string
    } & ProjectReference
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Cover
  | Figure
  | Slide
  | SanityFileAssetReference
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | Project
  | Slug
  | ProjectReference
  | Shelf
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: ../web/src/sanity/queries.ts
// Variable: SHELF_PAGE_QUERY
// Query: {    "settings": *[_id == "siteSettings"][0]{      siteTitle,      tagline,      intro,      colophon,      email,      githubUrl,      linkedinUrl    },    "shelves": *[_type == "shelf"] | order(order asc){      _id,      title,      "slug": slug.current,      caption,      itemStyle,      order,      items[]{        _key,        ...@->{          _id,          title,          "slug": slug.current,          coverTitle,          subtitle,          year,          presentation,          clothColor,          coverMotif,          coverImage{              asset->{    _id,    url,    metadata {      lqip,      dimensions {        width,        height,        aspectRatio      }    }  },  alt,  crop,  hotspot          }        }      }    }  }
export type SHELF_PAGE_QUERY_RESULT = {
  settings:
    | {
        siteTitle: null
        tagline: null
        intro: null
        colophon: null
        email: null
        githubUrl: null
        linkedinUrl: null
      }
    | {
        siteTitle: string
        tagline: string | null
        intro: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'normal'
          listItem?: never
          markDefs?: null
          level?: number
          _type: 'block'
          _key: string
        }> | null
        colophon: string | null
        email: string | null
        githubUrl: string | null
        linkedinUrl: string | null
      }
    | null
  shelves: Array<{
    _id: string
    title: string
    slug: string
    caption: string | null
    itemStyle: 'book' | 'manuscript'
    order: number
    items: Array<{
      _key: string
      _id: string
      title: string
      slug: string
      coverTitle: string | null
      subtitle: string | null
      year: string | null
      presentation: 'book' | 'inherit' | 'manuscript' | null
      clothColor:
        'bay-blue' | 'berkshires-green' | 'duckling-yellow' | 'independence-cranberry' | 'ink'
      coverMotif: 'centered-dot' | 'corner-rules' | 'double-rule' | 'none' | null
      coverImage: {
        asset: {
          _id: string
          url: string
          metadata: {
            lqip: string | null
            dimensions: {
              width: number
              height: number
              aspectRatio: number
            } | null
          } | null
        } | null
        alt: string
        crop: SanityImageCrop | null
        hotspot: SanityImageHotspot | null
      } | null
    }> | null
  }>
}

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  {\n    "settings": *[_id == "siteSettings"][0]{\n      siteTitle,\n      tagline,\n      intro,\n      colophon,\n      email,\n      githubUrl,\n      linkedinUrl\n    },\n    "shelves": *[_type == "shelf"] | order(order asc){\n      _id,\n      title,\n      "slug": slug.current,\n      caption,\n      itemStyle,\n      order,\n      items[]{\n        _key,\n        ...@->{\n          _id,\n          title,\n          "slug": slug.current,\n          coverTitle,\n          subtitle,\n          year,\n          presentation,\n          clothColor,\n          coverMotif,\n          coverImage{\n            \n  asset->{\n    _id,\n    url,\n    metadata {\n      lqip,\n      dimensions {\n        width,\n        height,\n        aspectRatio\n      }\n    }\n  },\n  alt,\n  crop,\n  hotspot\n\n          }\n        }\n      }\n    }\n  }\n': SHELF_PAGE_QUERY_RESULT
  }
}
